/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 public/models/house.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function House(props) {
  const { nodes, materials } = useGLTF("./models/house.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Door.geometry} material={materials.Derevo} />
      <mesh
        geometry={nodes.Platform.geometry}
        material={materials.Gras}
        receiveShadow
      />
      <mesh geometry={nodes.Roof.geometry} material={materials.Roof} />
      <mesh geometry={nodes.Roofs_2.geometry} material={materials.Roof} />
      <mesh geometry={nodes.Stone.geometry} material={materials.Stone} />
      <mesh geometry={nodes.Stone_2.geometry} material={materials.Stone} />
      <mesh
        geometry={nodes.Stone_2001.geometry}
        material={materials.Stone}
        position={[2.004, 0, 10.483]}
        scale={2.09}
      />
      <mesh geometry={nodes.Stone_3.geometry} material={materials.Stone} />
      <mesh geometry={nodes.Window.geometry} material={materials.Derevo} />
      <mesh geometry={nodes.Cube031.geometry} material={materials.Derevo} />
      <mesh geometry={nodes.Cube031_1.geometry} material={materials.Metal} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Derevo} />
      <mesh geometry={nodes.Cube001_1.geometry} material={materials.Sten} />
      <mesh geometry={nodes.Cube001_2.geometry} material={materials.Stone} />
    </group>
  );
}

useGLTF.preload("./models/house.glb");
