/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 public/models/Ocean.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Ocean(props) {
  const { nodes, materials } = useGLTF("./models/Ocean.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ocean.geometry} material={materials.Water} />
    </group>
  );
}

useGLTF.preload("./models/Ocean.glb");
